FROM debian:stable-slim

RUN apt update && apt install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev curl

RUN curl https://bun.sh/install | bash

COPY . .

RUN bun install --production

CMD ["bun", "run", "src/index.ts"]