version: '3.8'

services:
  bot:
    image: imlightymc/hera
    environment:
      - botToken=<your bot token>
      - clientId=<your application client id>
      - clientSecret=<your application client secret>
      - environment=prod
      - guildId=<the bot's support guild id>
      - lavalinkHost=hera-lavalink
    networks:
      - lavalink
    depends_on:
      - lavalink
  lavalink:
    container_name: hera-lavalink
    image: ghcr.io/lavalink-devs/lavalink:v4
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx1G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    expose:
      - 2333
    networks:
      - lavalink

networks:
  lavalink:
    name: lavalink